version: "3"
services:
    nginx-winner:
        hostname: nginx-winner
        container_name: nginx-winner
        image: pat
        ports:
            - 8001:80
            - 9001:443
        volumes:
            - /data/platform/config/nginx-php/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /data/platform/config/nginx-php/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - /data/platform/config/nginx-php/etc/nginx/ssl:/etc/nginx/ssl
            - /data/platform/www:/usr/share/nginx/html
            - /raid:/raid
            - /data/platform/config/nginx-php/etc/php-fpm:/etc/php/7.1/fpm
            - /data/platform/log:/var/log/nginx
        environment:
            - TZ=Asia/Bangkok
        cap_add:
            - SYS_PTRACE
        restart: always
